{% set data = load_setup_py_data() %}

package:
    name    : whatrecord
    version : {{ data.get('version') }}

source:
    path: ..

build:
    number: 0

requirements:
    build:
      - python >=3.9
      - setuptools
      - epicscorelibs
      - cython
    run:
      - python >=3.9
      - aiohttp
      - cython
      - epicscorelibs
      - graphviz
      - jinja2

      # Not yet on conda-forge :(
      # - apischema
      # - lark

test:
    imports:
      - whatrecord
    requires:
      - pytest

about:
  home: https://github.com/pcdshub/whatrecord
  license: SLAC Open License
  summary: EPICS IOC record search and meta information tool
