{% set data = load_setup_py_data() %}

package:
    name: whatrecord
    version: {{ data.get('version') }}

source:
    path: ..

build:
    number: 0
    noarch: python

requirements:
    build:
      - python {{PY_VER}}*
      - pip
    run:
      - python {{PY_VER}}*
      - aiohttp
      - apischema
      - graphviz
      - jinja2
      - lark-parser
      - python-graphviz <0.18

test:
    imports:
      - whatrecord
    requires:
      - pytest
      - pytest-aiohttp
      - epics-base

about:
  home: https://github.com/pcdshub/whatrecord
  license: SLAC Open License
  summary: EPICS IOC record search and meta information tool
