{% set data = load_setup_py_data() %}

package:
    name    : whatrecord
    version : {{ data.get('version') }}

source:
    path: ..

build:
    number: 0

requirements:
    build:
      - python >=3.9
      - setuptools
      - epicscorelibs
      - setuptools_dso
      - cython
    run:
      - python >=3.9
      - aiohttp
      - graphviz
      - python-graphviz
      - jinja2
      - lark-parser <1.0
      - apischema <0.16

test:
    imports:
      - whatrecord
    requires:
      - pytest
      - pytest-aiohttp
      - epics-base

about:
  home: https://github.com/pcdshub/whatrecord
  license: SLAC Open License
  summary: EPICS IOC record search and meta information tool
